version: '3'

services:
  php:
    image: php:7.4-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    links:
      - db


  nginx:
    image: nginx:latest
    ports:
      - "6789:80"
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - ./src/nginx-logs:/var/log/nginx
    links:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "127.0.0.100:3306:3306"
    volumes:
      - ./src/mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge